apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: add-istio-labels
spec:
  rules:
  - name: add-istio-labels
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            app: "{{ request.object.metadata.labels.\"app.kubernetes.io/name\" }}"
            version: "{{ values(images.containers)[0].tag || values(images.containers)[0].digest }}"
