apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
  labels:
    app.kubernetes.io/name: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aggregator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aggregator
        app.kubernetes.io/part-of: ssi-kubernetes
    spec:
      containers:
      - name: aggregator
        image: ghcr.io/kuruyia/ssi-kubernetes/aggregator:latest
        imagePullPolicy: Always
        env:
          - name: BIND_ADDRESS
            value: "0.0.0.0:3010"
          - name: NOUNS_ADDRESS
            value: "http://nouns:3000"
          - name: VERBS_ADDRESS
            value: "http://verbs:3000"
        ports:
          - containerPort: 3010
            name: api
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
