apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: fifo

namespace: ssi-kubernetes
resources:
- ns.yml
- kyverno/add-securitycontext.yml
- kyverno/verify-image-signature.yml
- ../base

patches:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
  path: aggregator/no-ssl-redirect.patch.yml
