apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aggregator/deployment.yml
  - aggregator/ingress.yml
  - aggregator/svc.yml
  - nouns/deployment.yml
  - nouns/svc.yml
  - verbs/deployment.yml
  - verbs/svc.yml

labels:
  - pairs:
      app.kubernetes.io/part-of: ssi-kubernetes
