apiVersion: apps/v1
kind: Deployment
metadata:
  name: nouns
  labels:
    app.kubernetes.io/name: nouns
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nouns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nouns
        app.kubernetes.io/part-of: ssi-kubernetes
    spec:
      containers:
      - name: nouns
        image: ghcr.io/kuruyia/ssi-kubernetes/words:latest
        imagePullPolicy: Always
        env:
          - name: BIND_ADDRESS
            value: "0.0.0.0:3000"
          - name: KIND
            value: "nouns"
        ports:
          - containerPort: 3000
            name: api
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 5
